version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_USER: admin
      DB_HOST: db
      DB_NAME: mydatabase
      DB_PASSWORD: admin
      DB_PORT: 5432
      GEMINI_API_KEY: AIzaSyDOXnEP2ijkBL1ksn8eKYIZ5UIPpLpfwsI
    ports:
      - "3000:3000"
    depends_on:
      - db